apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    framework: nodejs
    type: HTTP
  name: nodejs-service.rules
spec:
  groups:
  - name: nodejs-service.rules
    rules:
    - alert: DesiredVsActualPods
      annotations:
        description: Desired pods for nodejs-service is larger than actual pods
          for too long. Please ensure everything is configured correctly.
        summary: Desired pods larger than actual pods - nodejs-service
      expr: |
        ((
          avg(avg_over_time(kube_horizontalpodautoscaler_status_desired_replicas{exported_namespace=~"nodejs-service"}[5m])) by (exported_namespace) /
          avg(avg_over_time(kube_deployment_spec_replicas{exported_namespace=~"nodejs-service"}[5m])) by (exported_namespace)
        ) or (
          avg(avg_over_time(kube_horizontalpodautoscaler_status_desired_replicas{namespace=~"nodejs-service"}[5m])) by (namespace) /
          avg(avg_over_time(kube_deployment_spec_replicas{namespace=~"nodejs-service"}[5m])) by (namespace)
        )) < 0.9
      for: 10m
      labels:
        owner: ops
        severity: warning
    - alert: HighMemoryConsumption
      annotations:
        description: |
          Memory usage {{ $value | humanizePercentage }} of {{ $labels.namespace }} for container {{ $labels.container }} is too high.
          Please check the service for memory leaks or increase the memory if needed.
        summary: |
          High memory usage - service {{ $labels.namespace }} / container {{ $labels.container }}
      expr: |
        (
          max(max_over_time(container_memory_usage_bytes{namespace="nodejs-service", container!=""}[5m])) by (namespace, container) /
          avg(avg_over_time(container_spec_memory_limit_bytes{namespace="nodejs-service", container!=""}[5m])) by (namespace, container)
        ) > 0.9
      for: 10m
      labels:
        owner: ops
        severity: warning
